[package]
name = "dosers"
version = "0.0.1"
authors = ["Pato Lankenau"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features =["json"] }
json = "0.12"
tokio = { version = "1.6", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"